### ISSUE TITLE
#3 Original Generated RDF File and the generator Description

### ISSUE THREAD

**Issue by MohamedRagabAnas** [tarlanhasanli/BSBMPerformanceMeasurement#3]
Please Upload in The Datsests folder the Original Generated RDF file. 
and TXT file to describe the generating data process.

**Comment by tarlanhasanli** [comment]
The generated file is in N-Triples format and added to the root directory. The description of all steps will be added to the README file soon.

**Comment by MohamedRagabAnas** [comment]
OK Thanks 👍
